image: thlmylab/swakkd:1.22

stages:                      # Stages for jobs, and their order of execution
  - check
  - component
  - deploy

variables:
  DEPLOY_REDIS: "true"       # deploys Redis if set to true
  DEPLOY_MONGO: "true"       # deploys Mongo if set to true

kubernetes:
  stage: check
  script:
    - NS=$(cat $KUBECONFIG | yq e '.contexts[0].context.namespace' - -e) || true
    - NS=${NS:='default'}
    - kubectl get nodes
    - kubectl get pods
    - echo "Great, kubectl seems to work with namespace $NS"

registry:
  stage: check
  script:
    - cd page
    - img login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - img build -t $CI_REGISTRY_IMAGE/welcome:latest .
    - img push $CI_REGISTRY_IMAGE/welcome:latest
    - echo "Great, image build and registry push seem to work for namespace $NS"

welcome-page:
  stage: deploy
  script:
    - NS=$(cat $KUBECONFIG | yq e '.contexts[0].context.namespace' - -e) || true
    - NS=${NS:='default'}
    - echo "Deploying to Kubernetes"
    - kubectl delete secret gitlab-registry-credentials -n $NS || true
    - kubectl create secret docker-registry gitlab-registry-credentials --docker-server=$CI_REGISTRY --docker-username=image-registry --docker-password=$CI_REGISTRY_TOKEN -n $NS
    - mo page/deploy/page-dep.yaml | kubectl delete -n $NS -f - || true
    - mo page/deploy/page-dep.yaml | kubectl apply -n $NS -f - 
    - mo page/deploy/page-svc.yaml | kubectl apply -n $NS -f -
    - mo page/deploy/page-ing.yaml | kubectl apply -n $NS -f -

redis:
  stage: component
  only:
    variables:
      - $DEPLOY_REDIS == "true"
  script:
    - NS=$(cat $KUBECONFIG | yq e '.contexts[0].context.namespace' - -e) || true
    - NS=${NS:='default'}
    - echo "Deploying Redis database component"
    - kubectl apply -n $NS -f redis/deploy/pvc.yaml 
    - kubectl apply -n $NS -f redis/deploy/ 

mongo:
  stage: component
  only:
    variables:
      - $DEPLOY_MONGO == "true"
  script:
    - NS=$(cat $KUBECONFIG | yq e '.contexts[0].context.namespace' - -e) || true
    - NS=${NS:='default'}
    - echo "Deploying Mongo database component"
    - kubectl apply -n $NS -f mongo/deploy/pvc.yaml 
    - kubectl apply -n $NS -f mongo/deploy/
