apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-express
spec:
  selector:
    matchLabels:
      app: nodejs-express
  template:
    metadata:
      labels:
        app: nodejs-express
    spec:
      imagePullSecrets: [{ name: gitlab-registry-credentials }]
      containers:
      - name: nodejs-express
        image: {{ CI_REGISTRY_IMAGE }}/nodejs-express:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
