apiVersion: apps/v1
kind: Deployment
metadata:
  name: onyx-redis
spec:
  selector:
    matchLabels:
      app: onyx-redis
  template:
    metadata:
      labels:
        app: onyx-redis
    spec:
      volumes:
      - name: database
        persistentVolumeClaim: { claimName: onyx-redis }
      containers:
      - name: redis
        image: redis:6.2-alpine
        command: ["redis-server", "--bind", "0.0.0.0", "--appendonly", "yes", "--save", "\"\"", "--loglevel", "verbose"]
        resources:
          limits:
            memory: "250Mi"
            cpu: "100m"
        ports: [{ containerPort: 6379 }]
        volumeMounts: [{ mountPath: "/data", name: "database" }]
