apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onyx-ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  rules:
  - host: welcome-{{ CI_PROJECT_ID }}.edu.k8s.th-luebeck.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: onyx-frontend
            port:
              number: 80
              
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: onyx-backend
            port:
              number: 44660
  tls:
  - hosts:
    - welcome-{{ CI_PROJECT_ID }}.edu.k8s.th-luebeck.dev
    secretName: ingress-tls-certificate