apiVersion: apps/v1
kind: Deployment
metadata:
  name: onyx-backend
  labels:
    app: onyx-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: onyx-backend
  template:
    metadata:
      labels:
        app: onyx-backend
    spec:
      containers:
      - name: onyx-backend
        image: schrotty/onyx-backend:latest
        env:
        - name: PORT
          value: "44660"
        - name: ONYX_LOG_LEVEL
          value: "INFO"
        ports:
        - containerPort: 44660
        readinessProbe:
          httpGet:
            path: /api/heartbeat
            port: 44660
        livenessProbe:
          httpGet:
            path: /api/heartbeat
            port: 44660
