apiVersion: apps/v1
kind: Deployment
metadata:
  name: onyx-backend
  labels:
    app: onyx-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: onyx-backend
  template:
    metadata:
      labels:
        app: onyx-backend
    spec:
      containers:
      - name: onyx-backend
        image: schrotty/onyx-backend:latest
        env:
        - name: PORT
          value: "44660"
        - name: ONYX_LOG_LEVEL
          value: "INFO"
        - name: ONYX_ENABLE_REDIS
          value: "true"
        - name: ONYX_REDIS_HOST
          value: welcome-{{ CI_PROJECT_ID }}.edu.k8s.th-luebeck.dev
        - name: ONYX_REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 44660
        readinessProbe:
          httpGet:
            path: /api/heartbeat
            port: 44660
        livenessProbe:
          httpGet:
            path: /api/heartbeat
            port: 44660
