apiVersion: apps/v1
kind: Deployment
metadata:
  name: onyx-backend
  labels:
    app: onyx-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: onyx-backend
  template:
    metadata:
      labels:
        app: onyx-backend
    spec:
      containers:
      - name: onyx-backend
        image: schrotty/onyx-backend:latest
        env:
        - name: PORT
          value: "8081"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /api/heartbeat
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
