apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
spec:
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
      - name: landing-page
        image: {{ $CI_REGISTRY_IMAGE/welcome }}
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
